version: 2
jobs:
  build:
    working_directory: /temp
    machine:
      image: circleci/classic:201708-01
    docker:
      - image: microsoft/aspnetcore-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run:
          name: Build docker image
          command: |
            docker build -t guillermocorrea/dockerdemo .
      - run:
          name: Test docker image
          command: |
            docker run -d -p 9200:9200 guillermocorrea/dockerdemo; sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:9200
      - run:
          name: Publish docker image
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker push guillermocorrea/dockerdemo