version: 2.0

jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/aspnetcore-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build docker image
          command: |
            docker build -t guillermocorrea/dockerdemo .
      - run:
          name: Test docker image
          command: |
            docker run -d -p 9200:9200 guillermocorrea/dockerdemo; sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:9200
      - run:
          name: Publish docker image
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker push guillermocorrea/dockerdemo

#  deploy:
#    docker:
#      - image: docker:17.05.0-ce-git
#    steps:
#      - checkout

#workflows:
#  version: 2
#  build-and-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
